# Generated by Django 3.1.1 on 2023-03-16 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AwsAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('arn_of_iam_role', models.CharField(max_length=100, unique=True)),
                ('bucket_name', models.CharField(max_length=100)),
                ('report_name', models.CharField(max_length=100)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('prefix_path', models.TextField(max_length=100)),
                ('role_session_name', models.TextField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_added_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'AwsAccounts',
                'ordering': ('created',),
            },
        ),
    ]
